### ISSUE TITLE
仓库命名问题

### ISSUE THREAD

**Issue by OliverWu515** [HITSZ-OpenAuto/PHYS1001A#1]
新的《大学物理》课程的课程代码有变动，是PHYS1005A（XA）和PHYS1005B（XB），但是PHYS1005 又被《物理学概论》占用。更何况还有 PHYS1007A（新IA）和 PHYS1007B（新IB）。那这个仓库如何命名？改名为 College_Physics？

**Comment by MaxwellJay256** [comment]
我觉得 PHYS1005X 是针对多数工科生是最合适的名字了
